export const productos = [
    {
        idProducto: 1, 
        nombre: "Luxury Gems Necklace",
        codigo: 11,
        precioUnitario: "$168.76",
        tipoDeAccesorio: "Necklaces",
        descripcion: "Collar de gemas",
        imagen: "",
        cantidadEnStock: 10,
    },
    {
        idProducto: 2, 
        nombre: "Aurora Ring",
        codigo: 12,
        precioUnitario: "$125.28",
        tipoDeAccesorio: "Rings",
        descripcion: "Anillo de perlas",
        cantidadEnStock: 10,
    },
    {
        idProducto: 3, 
        nombre: "Reflections Necklace",
        codigo: 13,
        precioUnitario: "$620.73",
        tipoDeAccesorio: "Necklaces",
        descripcion: "Collar liso",
        cantidadEnStock: 10,
    },
    {
        idProducto: 4, 
        nombre: "Dreamy Infinite Ring",
        codigo: 14,
        precioUnitario: "$327.71",
        tipoDeAccesorio: "Rings",
        descripcion: "Anillo gema",
        cantidadEnStock: 10,
    },
    {
        idProducto: 5, 
        nombre: "Opulent Jewels Ring",
        codigo: 15,
        precioUnitario: "$168.76",
        tipoDeAccesorio: "Rings",
        descripcion: "Anillo liso",
        cantidadEnStock: 10,
    },
    {
        idProducto: 6, 
        nombre: "Serene Solitarie Earrings",
        codigo: 16,
        precioUnitario: "$125.28",
        tipoDeAccesorio: "Earrings",
        descripcion: "Aretes Piedra Preciosa",
        cantidadEnStock: 10,
    },
    {
        idProducto: 7, 
        nombre: "Timeless Halo Earrings",
        codigo: 17,
        precioUnitario: "$620.73",
        tipoDeAccesorio: "Earrings",
        descripcion: "Aretes Piedra Preciosa",
        cantidadEnStock: 10,
    },
    {
        idProducto: 8, 
        nombre: "Exquisite Earrings",
        codigo: 18,
        precioUnitario: "$327.71",
        tipoDeAccesorio: "Earrings",
        descripcion: "Aretes Piedra Preciosa",
        cantidadEnStock: 10,
    },
    {
        idProducto: 9, 
        nombre: "Timeless Elegance Rings",
        codigo: 19,
        precioUnitario: "$168.76",
        tipoDeAccesorio: "Rings",
        descripcion: "Anillo Piedras",
        cantidadEnStock: 10,
    },
    {
        idProducto: 10, 
        nombre: "Luxury Charms Ring",
        codigo: 110,
        precioUnitario: "$620.73",
        tipoDeAccesorio: "Rings",
        descripcion: "Anillo Piedra",
        cantidadEnStock: 10,
    },
    {
        idProducto: 11, 
        nombre: "Blissful Bloom Ring",
        codigo: 111,
        precioUnitario: "$620.73",
        tipoDeAccesorio: "Rings",
        descripcion: "Anillo Hojas",
        cantidadEnStock: 10,
    },
    {
        idProducto: 12, 
        nombre: "Sparkling Ring",
        codigo: 112,
        precioUnitario: "$620.73",
        tipoDeAccesorio: "Rings",
        descripcion: "Anillo Brillante",
        cantidadEnStock: 10,
    },
    {
        idProducto: 13, 
        nombre: "Glimmering Ring",
        codigo: 113,
        precioUnitario: "$620.73",
        tipoDeAccesorio: "Rings",
        descripcion: "Anillo Piedras",
        cantidadEnStock: 10,
    },
    {
        idProducto: 14, 
        nombre: "Bracelet",
        codigo: 114,
        precioUnitario: "$820.73",
        tipoDeAccesorio: "Bracelets",
        descripcion: "Abrazalete Piedras",
        cantidadEnStock: 10,
    }

];
